<a href="https://colab.research.google.com/github/manumc2306-sudo/Lenguaje-de-programacion/blob/main/Analisis_Cripto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Celda 1: instalar y importar
!pip install yfinance --quiet
import yfinance as yf
import pandas as pd
import numpy as np

print("¡Listo para analizar cripto!")

¡Listo para analizar cripto!

In [5]:
btc = yf.download('BTC-USD',
  start='2024-01-01',
  end='2024-12-31',
  interval='1d')

/tmp/ipykernel_10435/2245385042.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  btc = yf.download('BTC-USD',
[*********************100%***********************]  1 of 1 completed

In [6]:
btc.head()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2024-01-01,44167.332031,44175.437500,42214.976562,42280.234375,18426978443
2024-01-02,44957.968750,45899.707031,44176.949219,44187.140625,39335274536
2024-01-03,42848.175781,45503.242188,40813.535156,44961.601562,46342323118
2024-01-04,44179.921875,44770.023438,42675.175781,42855.816406,30448091210
2024-01-05,44162.691406,44353.285156,42784.718750,44192.980469,32336029347

In [7]:
btc.describe()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
count,365.000000,365.000000,365.000000,365.000000,3.650000e+02
mean,65888.868290,67114.172517,64434.563699,65751.583765,3.742215e+10
std,14632.134647,14920.310187,14310.209801,14618.657810,2.196309e+10
min,39507.367188,40127.351562,38521.894531,39518.714844,9.344044e+09
25%,59027.625000,60262.718750,57650.113281,59014.988281,2.384281e+10
50%,64118.792969,65523.222656,62783.632812,64104.738281,3.229276e+10
75%,69122.335938,70046.273438,67535.132812,69020.546875,4.314798e+10
max,106140.601562,108268.445312,105291.734375,106147.296875,1.492189e+11

In [8]:
btc.columns

MultiIndex([( 'Close', 'BTC-USD'),
            (  'High', 'BTC-USD'),
            (   'Low', 'BTC-USD'),
            (  'Open', 'BTC-USD'),
            ('Volume', 'BTC-USD')],
           names=['Price', 'Ticker'])

In [9]:
btc.shape

(365, 5)