<a href="https://colab.research.google.com/github/manumc2306-sudo/Lenguaje-de-programacion/blob/main/The_Trading_Floor_Experience_Criptomonedas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

¡Buenas tardes. Esperamos se encuentren muy bien!

Para dar inicio a nuestra presentacion, somos un equipo que ofrece su fondo de inversión en criptomonedas. Nuestra misión fue construir una aplicación interactiva que analiza datos históricos, de manera que propusimos una idea de trading y la defendemos hoy ante ustedes inversionistas del evento.

El pitch de nuestro fondo es que decidan dónde poner su capital de manera optima y a continuacion presentamos la mejor opcion.

In [2]:
# Celda 1: instalar y importar
!pip install yfinance --quiet
import yfinance as yf
import pandas as pd
import numpy as np

print("¡Listo para analizar cripto!")

¡Listo para analizar cripto!

In [12]:
import yfinance as yf

btc = yf.download('BTC-USD',
  start='2024-01-01',
  end='2024-12-31',
  interval='1wk')

eth = yf.download('ETH-USD',
  start='2024-01-01',
  end='2024-12-31',
  interval='1wk')

sol = yf.download('SOL-USD',
  start='2024-01-01',
  end='2024-12-31',
  interval='1wk')

ltc = yf.download('LTC-USD',
  start='2024-01-01',
  end='2024-12-31',
  interval='1wk')

/tmp/ipykernel_33471/2415062527.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  btc = yf.download('BTC-USD',
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_33471/2415062527.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  eth = yf.download('ETH-USD',
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_33471/2415062527.py:13: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sol = yf.download('SOL-USD',
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_33471/2415062527.py:18: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ltc = yf.download('LTC-USD',
[*********************100%***********************]  1 of 1 completed

In [13]:
btc.head()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2024-01-01,43943.097656,45899.707031,40813.535156,42280.234375,202311773985
2024-01-08,41796.269531,48969.371094,41724.613281,43948.707031,259971819745
2024-01-15,41545.785156,43566.273438,40297.457031,41715.066406,139135824835
2024-01-22,42035.593750,42797.175781,38521.894531,41553.652344,155314602893
2024-01-29,42583.582031,43838.945312,41818.332031,42030.914062,135184187433

In [14]:
eth.head()

Price             Close         High          Low         Open        Volume
Ticker          ETH-USD      ETH-USD      ETH-USD      ETH-USD       ETH-USD
Date
2024-01-01  2222.865967  2431.212402  2113.925293  2282.870361   73516556682
2024-01-08  2472.241211  2710.421875  2171.993652  2222.857666  125618508717
2024-01-15  2453.913086  2613.566895  2414.710938  2471.666992   64386569187
2024-01-22  2257.208740  2463.447266  2167.282471  2454.987305   71958589077
2024-01-29  2289.546143  2388.870605  2237.711670  2256.995361   56097099150

In [15]:
sol.head()

Price           Close        High        Low        Open       Volume
Ticker        SOL-USD     SOL-USD    SOL-USD     SOL-USD      SOL-USD
Date
2024-01-01  89.276344  116.882492  88.223457  101.512810  22230760995
2024-01-08  94.133141  106.935738  85.646698   89.278175  24098899954
2024-01-15  90.848434  102.923141  87.483658   94.036545  14197778980
2024-01-22  95.937981   99.377373  79.066696   90.903694  15388810594
2024-01-29  95.476959  106.213455  93.379189   95.937981  17926315542

In [16]:
ltc.head()

Price           Close       High        Low       Open      Volume
Ticker        LTC-USD    LTC-USD    LTC-USD    LTC-USD     LTC-USD
Date
2024-01-01  64.257469  75.808220  63.047882  72.913292  2760754636
2024-01-08  69.815598  76.847626  61.708389  64.254425  3866786915
2024-01-15  71.600082  72.674866  66.610962  69.796051  2326786847
2024-01-22  68.397507  72.544601  63.261303  71.614716  2075686085
2024-01-29  66.931389  69.796165  65.803146  68.391548  1694363742

In [19]:
# NombreTicker['Close'] tiene los precios de cierre
btc['retorno'] = btc['Close'].pct_change()
eth['retorno'] = eth['Close'].pct_change()
sol['retorno'] = sol['Close'].pct_change()
ltc['retorno'] = ltc['Close'].pct_change()